
### CREATE LOGIN ###
post http://localhost:3001/api/users
Content-Type: application/json

{
  "username" : "johnd",
  "name": "John Doe",
  "password": "8675"
}


### LOGIN ###
post http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "johnd",
  "password": "8675"
}
